In [1]:
import numpy as np

In [4]:
zp = np.array([35,45,190,200,40,70,54,150,120,110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
X = zp
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401,574,874,919,459,739,653,902,746,832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
y = ks
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [7]:
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [8]:
a = np.mean(y)-b*np.mean(X)
a

444.1773573243596

In [10]:
y_hat = 444.18 + 2.62*X
y_hat

array([535.88, 562.08, 941.98, 968.18, 548.98, 627.58, 585.66, 837.18,
       758.58, 732.38])

In [12]:
mse = ((y-y_hat)**2).sum()/10
mse

6470.417919999998

In [13]:
# без интерсепта

In [16]:
import seaborn as sns

In [18]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [19]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [20]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[5.88982042]])

In [21]:
y_hat = 5.89*X
y_hat

array([[ 206.15],
       [ 265.05],
       [1119.1 ],
       [1178.  ],
       [ 235.6 ],
       [ 412.3 ],
       [ 318.06],
       [ 883.5 ],
       [ 706.8 ],
       [ 647.9 ]])

In [22]:
mse = ((y-y_hat)**2).sum()/10
mse

56516.85886

In [23]:
# градиентный спуск без интерсепт

In [24]:
def mse_(B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [25]:
alpha = 1e-6
alpha

1e-06

In [26]:
B1=0.1

In [27]:
n=10

In [32]:
for i in range (500):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%10==0:
      print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration: 0, B1=5.873885137561711, mse=56520.35675226433
Iteration: 10, B1=5.877769553381888, mse=56518.85910026643
Iteration: 20, B1=5.880707096362074, mse=56518.00259913497
Iteration: 30, B1=5.882928578088004, mse=56517.512769595625
Iteration: 40, B1=5.884608547059329, mse=56517.232638059555
Iteration: 50, B1=5.885879003490128, mse=56517.072431964974
Iteration: 60, B1=5.8868397709626885, mse=56516.98081074626
Iteration: 70, B1=5.887566339866551, mse=56516.928412941146
Iteration: 80, B1=5.888115798905433, mse=56516.89844684794
Iteration: 90, B1=5.888531320728348, mse=56516.88130936019
Iteration: 100, B1=5.888845554134484, mse=56516.87150850017
Iteration: 110, B1=5.889083189387522, mse=56516.86590342786
Iteration: 120, B1=5.889262898203911, mse=56516.862697909644
Iteration: 130, B1=5.889398800845774, mse=56516.86086468671
Iteration: 140, B1=5.889501575592372, mse=56516.85981627392
Iteration: 150, B1=5.889579297764605, mse=56516.85921669088
Iteration: 160, B1=5.889638074227276, mse=565

In [33]:
y_hat = 5.89*X
y_hat

array([[ 206.15],
       [ 265.05],
       [1119.1 ],
       [1178.  ],
       [ 235.6 ],
       [ 412.3 ],
       [ 318.06],
       [ 883.5 ],
       [ 706.8 ],
       [ 647.9 ]])