In [1]:
# Введем массивы заработной платы zp и кредитного скоринга ks

In [2]:
import numpy as np

In [4]:
zp = np.array([35,45,190,200,40,70,54,150,120,110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
ks = np.array([401,574,874,919,459,739,653,902,746,832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [11]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [12]:
# корреляция зарплаты и скоринга оказалась значимой и положительной, т.е. между уровнем зарплаты и кредитным скорингом сильная прямая связь - чем больше з/п, тем выше скоринг

In [15]:
np.cov(zp,ks,ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [16]:
np.std(zp)

59.115480206118605

In [17]:
np.std(ks)

174.55340157098058