In [1]:
import numpy as np

In [4]:
x1 = [3, -1, 1]
y1 = [2, -5, -3]
z1 = [1, 1, -1]

x2 = [3, -1, 1, 4]
y2 = [2, -5, -3, -17]
z2 = [1, 1, -1, 0]


A = np.array([x1, y1, z1])
r1 = np.linalg.matrix_rank(A)

At = np.array([x2, y2, z2])
r2 = np.linalg.matrix_rank(At)

print(f'Ранг матрицы A: {r1}')

print(f'Ранг матрицы At: {r2}')

Ранг матрицы A: 3
Ранг матрицы At: 3


In [11]:
# ранги равны, число неизвестных n = 3 = rank, значит, система совместна, и имеется 1 решение

In [5]:
x1 = [2, -4, 6]
y1 = [1, -2, 3]
z1 = [3, -6, 9]

x2 = [2, -4, 6, 1]
y2 = [1, -2, 3, -2]
z2 = [3, -6, 9, 5]


A = np.array([x1, y1, z1])
r1 = np.linalg.matrix_rank(A)

At = np.array([x2, y2, z2])
r2 = np.linalg.matrix_rank(At)

print(f'Ранг матрицы A: {r1}')

print(f'Ранг матрицы At: {r2}')

Ранг матрицы A: 1
Ранг матрицы At: 2


In [6]:
# ранг расширенной матрицы At > матрицы A, значит, система несовместна, решений нет

In [7]:
x1 = [1, 2, 5]
y1 = [3, 1, -8]

x2 = [1, 2, 5, 4]
y2 = [3, 1, -8, -2]

A = np.array([x1, y1])
r1 = np.linalg.matrix_rank(A)

At = np.array([x2, y2])
r2 = np.linalg.matrix_rank(At)

print(f'Ранг матрицы A: {r1}')

print(f'Ранг матрицы At: {r2}')

Ранг матрицы A: 2
Ранг матрицы At: 2


In [8]:
# ранги равны, число неизвестных n = 3 > rank, значит, система совместна, и имеется множество решений

In [9]:
x1 = [1, 3, -2, 4]
y1 = [0, 5, 0, 1]
z1 = [0, 0, 3, 0]
c1 = [0, 0, 0, 2]

x2 = [1, 3, -2, 4, 3]
y2 = [0, 5, 0, 1, 2]
z2 = [0, 0, 3, 0, 4]
c2 = [0, 0, 0, 2, 1]


A = np.array([x1, y1, z1, c1])
r1 = np.linalg.matrix_rank(A)

At = np.array([x2, y2, z2, c2])
r2 = np.linalg.matrix_rank(At)

print(f'Ранг матрицы A: {r1}')

print(f'Ранг матрицы At: {r2}')

Ранг матрицы A: 4
Ранг матрицы At: 4


In [10]:
# ранги равны, число неизвестных n = 4 = rank, значит, система совместна, и имеется 1 решение

In [4]:
# решить систему уравнений методом Крамера

In [5]:
import numpy as np

In [9]:
a = np.array([[1, -2], [3, -4]])
b = np.array([[1, -2], [7, -4]])
c = np.array([[1, 1], [3, 7]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[ 1 -2]
 [ 3 -4]]
Матрица:
[[ 1 -2]
 [ 7 -4]]
Матрица:
[[1 1]
 [3 7]]
Определитель:
2
Определитель:
10
Определитель:
4


In [16]:
x1 = (np.linalg.det(b))/(np.linalg.det(a))
x2 = (np.linalg.det(c))/(np.linalg.det(a))
print(f'x1 = {round(x1,1)}')
print(f'x2 = {round(x2,1)}')

x1 = 5.0
x2 = 2.0


In [18]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
c = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
d = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')
print(f'Матрица:\n{c}')
print(f'Матрица:\n{d}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')
print(f'Определитель:\n{np.linalg.det(d):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель:
43
Определитель:
86
Определитель:
-43
Определитель:
43


In [20]:
x1 = (np.linalg.det(b))/(np.linalg.det(a))
x2 = (np.linalg.det(c))/(np.linalg.det(a))
x3 = (np.linalg.det(d))/(np.linalg.det(a))
print(f'x1 = {round(x1,1)}')
print(f'x2 = {round(x2,1)}')
print(f'x3 = {round(x3,1)}')

x1 = 2.0
x2 = -1.0
x3 = 1.0
